language: python
sudo: false

python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial  # https://github.com/travis-ci/travis-ci/issues/9815
      sudo: true

install:
  - pip install -U setuptools coveralls
  - pip install -Ue .[dev]

# command to run tests
script:
  - pytest
  - coveralls
